services:

  springboot:
    image: galplatform.azurecr.io/backend:latest
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      SUPABASE_JWKS_URI: ${SUPABASE_JWKS_URI}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

  grading-agent:
    image: galplatform.azurecr.io/grading-agent:latest
    ports:
      - "8000:8000"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      redis_host: ${redis_host}
      redis_port: ${redis_port}
      redis_password: ${redis_password}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:80,http://localhost:5173}
    restart: unless-stopped

  frontend:
    image: galplatform.azurecr.io/frontend:latest
    ports:
      - "80:80"
    restart: unless-stopped

